config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'registers#index'
  resources :registers 
  resources :parent_books do
    resources :teacher_comments 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '登園' },
    { id: 3, name: 'お休み' },
  ]
  
  include ActiveHash::Associations
  has_many :parent_books

  end

app/models/greeted_time.rb
class GreetedTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '16時頃' },
    { id: 3, name: '17時頃' },
    { id: 4, name: '18時頃' },
    { id: 5, name: 'それ以外' },
  ]

  include ActiveHash::Associations
  has_many :parent_books
  
  end

app/models/mood.rb
class Mood < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '良い' },
    { id: 3, name: '普通' },
    { id: 4, name: '悪い' },
  ]

  include ActiveHash::Associations
  has_many :parent_books

  end

app/models/parent_book.rb
class ParentBook < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :mood
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :greeted_time
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :attendance

  validates :parent_name, :parent_comment, :tell_number, presence: true
  validates :attendance_id, numericality: { other_than: 1, message: "can't be blank" } 
  validates :tell_number, format: {with:/\A\d{10,11}\z/}

  belongs_to :user
  belongs_to :register, optional: true
  has_many :teacher_comments, dependent: :destroy
end

app/models/poop.rb
class Poop < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '良い' },
    { id: 3, name: '普通' },
    { id: 4, name: '悪い' },
  ]

  include ActiveHash::Associations
  has_many :parent_books

  end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :user
  has_many :parent_books
  has_one_attached :image

  validates :title, presence: true
  validates :general_comment, presence: true
end

app/models/teacher_comment.rb
class TeacherComment < ApplicationRecord
  belongs_to :user
  belongs_to :parent_book

  validates :teacher_name, presence: true
  validates :teacher_comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :registers
  has_many :parent_books
  has_many :teacher_comments

  validates :birthday, presence: true
  validates :image,    presence: true

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ } do
    validates :last_name
    validates :first_name
  end
  
  with_options presence: true, format: { with: /\A[ァ-ヶー]+\z/ } do
    validates :last_name_kana
    validates :first_name_kana
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!



  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :birthday, :image, ])
  end

  end

app/controllers/parent_books_controller.rb
class ParentBooksController < ApplicationController
  before_action :set_parent_book, only: [:edit, :show, :update ]

  def index
    @parent_books = ParentBook.where(user_id: current_user.id).order("created_at DESC")
    if current_user.admin?
      redirect_to root_path
    end
  end

  def new
    @parent_book = ParentBook.new
  end

  def create
    @parent_book = ParentBook.new(parent_book_params)
    if @parent_book.save
      redirect_to parent_books_path
    else
      render :new
    end
  end

  def show
    @teacher_comment = TeacherComment.new
    @teacher_comments = @parent_book.teacher_comments.includes(:user)
  end

  def destroy
    parent_book = ParentBook.find(params[:id])
    if parent_book.destroy
      redirect_to parent_books_path
    end
  end

  def edit
  end

  def update
    if @parent_book.update(parent_book_params)
      redirect_to parent_books_path
    else
      render :edit
    end
  end

  private

  def parent_book_params
    params.require(:parent_book).permit(:parent_name, :parent_comment, :temperature, :mood_id, :breakfast, :attendance_id, :greeted_time_id, :greeted_name, :tell_number).merge(user_id: current_user.id, register_id: params[:register_id])
  end

  def set_parent_book
    @parent_book = ParentBook.find(params[:id])
  end

end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:edit, :show, :update ]

  def index
    @user = User.where(id: current_user.id).first
    @users = User.where.not(admin: true)
    @registers = Register.all
    @parent_book = ParentBook.where(user_id: current_user.id).last
    @parent_books = ParentBook.includes(:user).order("created_at DESC")
  end

  def new
    @register = Register.new
  end

  def create
    @register = Register.new(register_params)
    if @register.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @register.update(register_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    register = Register.find(params[:id])
    if register.destroy
      redirect_to root_path
    end
  end

  private
  def register_params
    params.require(:register).permit(:title, :general_comment, :image).merge(user_id: current_user.id)
  end

  def set_register
    @register = Register.find(params[:id])
  end
end

app/controllers/teacher_comments_controller.rb
class TeacherCommentsController < ApplicationController

  def create
    @parent_book = ParentBook.find(params[:parent_book_id])
    @teacher_comment = @parent_book.teacher_comments.new(teacher_comment_params)
    @teacher_comment.save
    redirect_to parent_book_path(@parent_book)
  end

  private
  def teacher_comment_params
    params.require(:teacher_comment).permit(:teacher_comment, :teacher_name).merge(user_id: current_user.id, parent_book_id: params[:parent_book_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parent_books_helper.rb
module ParentBooksHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/teacher_comments_helper.rb
module TeacherCommentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CONTACT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">   
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class='top-page-header'>
    <div class='nav'>
     <div class='class_name'>
        <%= link_to 'CONTACT', root_path, class: "class_name" %>
     </div>
     <ul class='lists-right'>
       <% if user_signed_in? %>
        <li><%= link_to current_user.first_name, "/", class: "header-btn" %></li> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "header-btn" %></li> 
       <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "header-btn" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "header-btn" %></li>
       <% end %>
       <% if user_signed_in? %>
         <% if current_user.admin? %>
           <%= link_to '投稿する', new_register_path, class: "header-btn" %>
         <% end %>
       <% end %>
     </ul>
    </div>
   </header>
    <%= yield %>
  </body>
</html>

app/views/parent_books/edit.html.erb
<div class="parent-book-contents">
  <div class="parent-book-header">
    ご家庭から
  </div>

  <div class="parent-book-main">
    <h2 class="parent-book-title">情報を入力</h2>
    <h3 class="parent-sub-title">※お休みする場合は「出欠確認・記入者名・ご家庭での様子」のみ記入してください※</h3>
    
    <%= form_with model: @parent_book, url: parent_book_path, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>


    <div class="new-book">
       <div class="book-detail">     
         <div class="weight-bold-text">
            出欠確認
            <span class="indispensable">必須</span>
         </div>
         <%= f.collection_select(:attendance_id, Attendance.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
       </div>

      <div class="weight-bold-text">
        記入者名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :parent_name, class:"book-text", id:"item-name" %>

      <div class="weight-bold-text">
          ご家庭での様子
          <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :parent_comment, class:"book-text", id:"item-info" %>

      <div class="weight-bold-text">
        体温
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :temperature, class:"book-text", id:"item-name", placeholder:"記入例）36.5度" %>

      <div class="weight-bold-text">
        朝食
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :breakfast, class:"book-text", id:"item-name" %>

      <div class="book-detail">
          <div class="weight-bold-text">
            機嫌
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:mood_id, Mood.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="book-detail">
          <div class="weight-bold-text">
            お迎え時間
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:greeted_time_id, GreetedTime.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="weight-bold-text">
        お迎えに来る人
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :greeted_name, class:"book-text", id:"item-name" %>

      <div class='weight-bold-text'>
        緊急連絡先
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :tell_number, class:"book-text", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
    </div>





 
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "提出する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/parent_books/index.html.erb
<div class='new-main'>
  <%# フォーム %>
  <div class='parent-form'>
    <%# フォームのヘッダー表示 %>
    <div class='form-top'>
      <div class='form-top-title'>
        家庭用連絡帳一覧
      </div>
    </div>

    <%# フォームのメイン部分 %>
    <div class='parent-form-main'>
    <% if user_signed_in?  %>
     <% @parent_books.each do |parent_book| %>
      <div class="form-list">
       <div class="child-condition">
         <%= link_to parent_book.attendance.name, parent_book_path(parent_book.id) %>
       </div>
       <div class="post-date">
         <%= parent_book.created_at.strftime("%Y/%m/%d") %>
       </div>
      </div>
      <% end %>
    <% end %>
    </div>
  </div>

  <div class="btn-area">
    <%= link_to "新規投稿", new_parent_book_path ,class:"parent-red-btn"%>
  </div>
</div>

app/views/parent_books/new.html.erb
<div class="parent-book-contents">
  <div class="parent-book-header">
    ご家庭から
  </div>

  <div class="parent-book-main">
    <h2 class="parent-book-title">情報を入力</h2>
    <h3 class="parent-sub-title">※お休みする場合は「出欠確認・記入者名・緊急連絡先・ご家庭での様子」のみ記入してください※</h3>
    
    <%= form_with model: @parent_book, url: parent_books_path, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>


    <div class="new-book">
       <div class="book-detail">     
         <div class="weight-bold-text">
            出欠確認
            <span class="indispensable">必須</span>
         </div>
         <%= f.collection_select(:attendance_id, Attendance.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
       </div>

      <div class="weight-bold-text">
        記入者名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :parent_name, class:"book-text", id:"item-name" %>

      <div class='weight-bold-text'>
        緊急連絡先
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :tell_number, class:"book-text", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>

      <div class="weight-bold-text">
          ご家庭での様子
          <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :parent_comment, class:"book-text", id:"item-info" %>

      <div class="weight-bold-text">
        体温
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :temperature, class:"book-text", id:"item-name", placeholder:"記入例）36.5度" %>

      <div class="weight-bold-text">
        朝食
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :breakfast, class:"book-text", id:"item-name" %>

      <div class="book-detail">
          <div class="weight-bold-text">
            機嫌
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:mood_id, Mood.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="book-detail">
          <div class="weight-bold-text">
            お迎え時間
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:greeted_time_id, GreetedTime.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="weight-bold-text">
        お迎えに来る人
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :greeted_name, class:"book-text", id:"item-name" %>

    </div>





 
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "提出する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/parent_books/show.html.erb
<div class="parent_book-show">
  <div class="book-box">
    <h2 class="name">
      <%= link_to @parent_book.user.first_name,  parent_books_path %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @parent_book.user.image ,class:"parent-box-img" %>
    </div>
    <% unless current_user.admin? %>
        <%= link_to "編集", edit_parent_book_path(@parent_book.id), method: :get, class: "parent-red-btn" %>
        <%= link_to "削除", parent_book_path(@parent_book.id), method: :delete, class:"parent-destroy" %>
    <% end %>
    <div class="parent-explain-box">
      <span>入力情報</span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出欠</th>
          <td class="detail-value"><%= @parent_book.attendance.name %></td>
        </tr>
        <tr>
          <th class="detail-item">記入者名</th>
          <td class="detail-value"><%= @parent_book.parent_name %></td>
        </tr>
        <tr>
          <th class="detail-item">家庭での様子</th>
          <td class="detail-value"><%= @parent_book.parent_comment %></td>
        </tr>
        <tr>
          <th class="detail-item">体温</th>
          <td class="detail-value"><%= @parent_book.temperature %></td>
        </tr>
        <tr>
          <th class="detail-item">朝食</th>
          <td class="detail-value"><%= @parent_book.breakfast %></td>
        </tr>
        <tr>
          <th class="detail-item">機嫌</th>
          <td class="detail-value"><%= @parent_book.mood.name %></td>
        </tr>
        <tr>
          <th class="detail-item">お迎え時間</th>
          <td class="detail-value"><%= @parent_book.greeted_time.name %></td>
        </tr>
        <tr>
          <th class="detail-item">お迎えに来る人</th>
          <td class="detail-value"><%= @parent_book.greeted_name %></td>
        </tr>
        <tr>
          <th class="detail-item">緊急連絡先</th>
          <td class="detail-value"><%= @parent_book.tell_number %></td>
        </tr>
      </tbody>
    </table>
    <% if user_signed_in? && current_user.admin?%>
    <div class="teacher-comment-form">
         <%= form_with(model: [@parent_book, @teacher_comment], local: true) do |form| %>
           <%= form.text_field :teacher_name, placeholder: "先生の名前" %>
           <%= form.text_area :teacher_comment, placeholder: "コメントする" %>
           <%= form.submit "SEND" %>
         <% end %>
    <% end %>
       <div class="teacher-comments">
         <h4>＜園から＞</h4>
         <% @teacher_comments.each do |teacher_comment| %>
           <p>
             <strong><%= teacher_comment.teacher_name %><br></strong>
             <%= teacher_comment.teacher_comment %>
           </p>
         <% end %>
       </div>
     </div>
  </div>
</div>

app/views/registers/_register.html.erb
<% if user_signed_in? && current_user.admin? %>
<div class="card">
  <div class="child-name-box">
      <%= user.last_name %>
  </div>
  <%= link_to image_tag(user.image, class: :card__img ), parent_books_path %>
  <% if @parent_book.present?%>
  <div class="today-info">
     <div class="register-explain-box">
      <span>今日の状況</span>
     </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出欠</th>
          <td class="detail-value"><%= @parent_book.attendance.name %></td>
        </tr>
        <tr>
          <th class="detail-item">体温</th>
          <td class="detail-value"><%= @parent_book.temperature %></td>
        </tr>
       
        <tr>
          <th class="detail-item">迎え時間</th>
          <td class="detail-value"><%= @parent_book.greeted_time.name %></td>
        </tr>
        <tr>
          <th class="detail-item">迎えに来る人</th>
          <td class="detail-value"><%= @parent_book.greeted_name %></td>
        </tr>
        <tr>
          <th class="detail-item">連絡先</th>
          <td class="detail-value"><%= @parent_book.tell_number %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <% end %>
</div>
<% end %>

app/views/registers/edit.html.erb
<div class='new-main'>
  <%# フォーム %>
  <div class='form'>
    <%# フォームのヘッダー表示 %>
    <div class='form-top'>
      <div class='form-top-title'>
        全体のお知らせ
      </div>
    </div>

    <%# フォームのメイン部分 %>
    <div class='form-main'>
      <%= form_with model: @register, local: true do |form| %>
      <%= render 'shared/error_messages', model: form.object %>
        <div class='input-items'>
          <div class='input-items__title'>
            <%= form.text_field :title, placeholder: "タイトル" %>
          </div>
          <div class='input-items__content'>
            <%= form.text_area :general_comment, placeholder: "お知らせ" %>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
               <label class="form-text">画像</label>
            </div>
          <div class="click-upload">
            <p>
              クリックしてファイルをアップロード
            </p>
            <%= form.file_field :image, id:"item-image" %>
          </div>
        </div>
          <div class='input-items__submit'>
            <%= form.submit 'POST'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/registers/index.html.erb
<%# 一覧表示画面 %>
<div class='index-main'>
  <div class='general_information'>
    ＜全体のお知らせ＞
  </div>
  <div class='post-contents'>
  <% if @registers.present? %>
    <% @registers.each do |register| %>
      <%# 投稿１件分の表示 %>
      <div class='post-content'>
        <%# 質問本文の表示 %>
        <div class='post-list'>
          <div class='post-top'>
            <div class='post-top__title'>
              <%= link_to "#{register.title}", register_path(register.id), method: :get %>
            </div>
            <div class="question-top__name">
              <%= register.created_at.strftime("%Y/%m/%d") %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% else %>
      <div class='post-content'>
        <%# 質問本文の表示 %>
        <div class='post-list'>
          <div class='post-top'>
            <div class='post-top__title_none'>
              お知らせはありません
            </div>
        </div>
      </div>
   </div>
   <% end %>
  <%#連絡帳%>
  <% if user_signed_in? && current_user.admin? %>
  <div class="list-main">
    <div class='parent-form'>
      <div class='form-top'>
        <div class='form-top-title'>
          連絡帳一覧
        </div>
      </div>
      <div class="admin-form-main">
      <% @parent_books.each do |parent_book|%>
         <div class="admin-form-list">
           <div class="child-condition">
             <%= link_to parent_book.user.first_name, parent_book_path(parent_book.id) %>
           </div>
           <div class="attendance">
             <%= parent_book.attendance.name %>
           </div>
           <div class="tempereture">
             <%= parent_book.temperature %>
           </div>
           <div class="greeted_time">
             <%= parent_book.greeted_time.name %>
           </div>
           <div class="post-date">
             <%= parent_book.created_at.strftime("%Y/%m/%d") %>
           </div>
         </div>
      <% end %> 
      </div>
    </div>
  </div>
  <% end %>
  <%#%>

  <div class='children_zone'>
  <%# 管理者画面 %>
    <% if user_signed_in? && current_user.admin? %>
    <div class = "children">
      ＜子どもたち＞
    </div>
    <div class ="user__card_area">
       <% @users.each do |user| %>
       <div class ="child_list">
         <div class ="card">
           <div class ="child-name-box">
             <%= user.first_name %>
           </div>
           <%= image_tag(user.image, class: :card__img ) %>
         </div>
       </div>
       <% end %>
      <%#%>
       <%# 親でログイン時%>
       <% else user_signed_in? %>
       <div class="child_list">
       <div class="card">
          <div class="child-name-box">
            <%= @user.first_name %>
          </div>
          <%= link_to image_tag(@user.image, class: :card__img ), parent_books_path %>
          <% if @parent_book.present?%>
          <div class="today-info">
             <div class="register-explain-box">
               <span>今日の状況</span>
             </div>
             <table class="detail-table">
               <tbody>
                 <tr>
                   <th class="detail-item">出欠</th>
                   <td class="detail-value"><%= @parent_book.attendance.name %></td>
                 </tr>
                 <tr>
                   <th class="detail-item">体温</th>
                   <td class="detail-value"><%= @parent_book.temperature %></td>
                 </tr>
                 <tr>
                   <th class="detail-item">迎え時間</th>
                   <td class="detail-value"><%= @parent_book.greeted_time.name %></td>
                 </tr>
                 <tr>
                   <th class="detail-item">迎えに来る人</th>
                   <td class="detail-value"><%= @parent_book.greeted_name %></td>
                 </tr>
                 <tr>
                   <th class="detail-item">連絡先</th>
                   <td class="detail-value"><%= @parent_book.tell_number %></td>
                 </tr>
               </tbody>
             </table>
          </div>
          <% end %>
       </div>
       </div>
       <% end %>
       <%# 親%>
    </div>
   </div>
</div>

app/views/registers/new.html.erb
<div class='new-main'>
  <%# フォーム %>
  <div class='form'>
    <%# フォームのヘッダー表示 %>
    <div class='form-top'>
      <div class='form-top-title'>
        全体のお知らせ
      </div>
    </div>

    <%# フォームのメイン部分 %>
    <div class='form-main'>
      <%= form_with model: @register, local: true do |form| %>
      <%= render 'shared/error_messages', model: form.object %>
        <div class='input-items'>
          <div class='input-items__title'>
            <%= form.text_field :title, placeholder: "タイトル" %>
          </div>
          <div class='input-items__content'>
            <%= form.text_area :general_comment, placeholder: "お知らせ" %>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
               <label class="image-form-text">画像</label>
            </div>
          <div class="click-upload">
            <p>
              クリックしてファイルをアップロード
            </p>
            <%= form.file_field :image, id:"item-image" %>
          </div>
        </div>
          <div class='input-items__submit'>
            <%= form.submit 'POST'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/registers/show.html.erb
<div class="main">
  <div class="inner">
    <div class="register__wrapper">
      <p class="register__heading">
        <%= @register.title %>
      </p>    
      <% if user_signed_in? && current_user.admin?%>
      <div class="register__manage">
          <%= link_to "編集する", edit_register_path(@register.id), method: :get, class: :register__btn %>
          <%= link_to "削除する",  register_path(@register.id), method: :delete, class: :register__btn %>
      </div>
      <% end %>
    </div>
    <div class="register-form">
      <div class='register-form-top'>
        <div class='register-top-title'>
          コメント
        </div>
      </div>
      <div class='register-form-main'>
        <div class="register-comment">
          <%= @register.general_comment %>
        </div>
      </div>
      <% if @register.image.presence %>
        <div class="register__image">
          <%= image_tag @register.image %>
        </div>
      <% else %>
        <div class="blank">画像はありません</div>
      <% end %> 
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>